name: Update translation data
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  push:
    branches: [dev]
    paths:
      - skills.txt
      - scripts/**
      - ovos_localize/**

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install package
        run: pip install -e ".[dev]" --pre -c https://raw.githubusercontent.com/OpenVoiceOS/OpenVoiceOS/refs/heads/main/constraints-alpha.txt

      - name: Generate data
        run: python scripts/generate_data.py
        env:
          GIT_TERMINAL_PROMPT: 0

      - name: Generate ML datasets
        run: python scripts/generate_datasets.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update translation data"
          file_pattern: "data/**"
